# Generated by Django 6.0.2 on 2026-02-24 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studybuddy.userprofile')),
                ('teaching_level', models.CharField(max_length=100)),
                ('can_online', models.BooleanField(default=True)),
                ('can_f2f', models.BooleanField(default=False)),
                ('rating_average', models.FloatField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_sessions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Tutee', 'Tutee'), ('Tutor', 'Tutor'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
