# Generated by Django 6.0.2 on 2026-02-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0004_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise_level', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studybuddy.subjects')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studybuddy.tutor')),
            ],
        ),
    ]
