# Generated by Django 6.0.2 on 2026-02-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0010_userprofile_bio_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoravailability',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='Mon', max_length=3),
            preserve_default=False,
        ),
    ]
