# Generated by Django 6.0.2 on 2026-02-27 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0011_tutoravailability_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoravailability',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studybuddy.tutor'),
        ),
    ]
