# Generated by Django 6.0.2 on 2026-02-28 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0012_alter_tutoravailability_tutor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tutoravailability',
            unique_together={('tutor', 'day', 'time_slot')},
        ),
        migrations.AlterField(
            model_name='booking',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='studybuddy.tutoravailability'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('availability', 'session_date')},
        ),
        migrations.RemoveField(
            model_name='tutoravailability',
            name='day_of_week',
        ),
    ]
