# Generated by Django 6.0.2 on 2026-03-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0014_paymentmethod_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('GCASH', 'GCash'), ('BANK', 'Bank Transfer')], max_length=20, null=True, unique=True),
        ),
    ]
