# Generated by Django 6.0.2 on 2026-03-04 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0017_userprofile_profile_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_mode', models.CharField(choices=[('Online', 'Online'), ('F2F', 'Face-to-Face')], max_length=10)),
                ('hourly_budget', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subjects', models.ManyToManyField(to='studybuddy.subjects')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studybuddy.userprofile')),
            ],
        ),
    ]
