# Generated by Django 6.0.2 on 2026-03-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0018_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='teaching_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
