# Generated by Django 6.0.2 on 2026-03-04 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0019_alter_tutor_hourly_rate_alter_tutor_teaching_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('strand_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('strand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studybuddy.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='strand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studybuddy.strand'),
        ),
    ]
