# Generated by Django 6.0.2 on 2026-03-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0020_course_strand_alter_userprofile_course_course_strand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='hourly_budget',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='preferred_mode',
        ),
    ]
