# Generated by Django 6.0.2 on 2026-04-06 13:48
# NOTE: This migration is a sibling of 0022_partnerinstitution_userprofile_institution_and_more.
# Both were created from the same base (0021). The 0023_merge migration joins them.
# This migration is intentionally empty because the other 0022 branch already
# creates PartnerInstitution and the two fields. The merge (0023) is the authoritative leaf.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0021_remove_preference_hourly_budget_and_more'),
    ]

    operations = [
    ]
