# Generated by Django 6.0.2 on 2026-04-06 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0021_remove_preference_hourly_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('school_email_domain', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['institution_name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_domain_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studybuddy.partnerinstitution'),
        ),
    ]
