# Generated by Django 6.0.2 on 2026-04-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0022_partnerinstitution_userprofile_institution_and_more'),
        ('studybuddy', '0022_partnerinstitution_userprofile_is_domain_exempt_and_more'),
    ]

    operations = [
    ]
