# Generated by Django 6.0.2 on 2026-04-25 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0034_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='tutee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutee_chat_rooms', to='studybuddy.userprofile'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_chat_rooms', to='studybuddy.userprofile'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='studybuddy.booking'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', True)), fields=('tutee', 'tutor'), name='unique_inquiry_chat'),
        ),
    ]
