# Generated by Django 6.0.2 on 2026-04-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0035_chatroom_tutee_chatroom_tutor_alter_chatroom_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='tutee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutee_chat_rooms', to='studybuddy.userprofile'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_chat_rooms', to='studybuddy.userprofile'),
        ),
    ]
