# Generated by Django 6.0.2 on 2026-04-25 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0036_alter_chatroom_tutee_alter_chatroom_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='tutee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutee_chat_rooms', to='studybuddy.userprofile'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_chat_rooms', to='studybuddy.userprofile'),
        ),
    ]
