# Generated by Django 6.0.2 on 2026-04-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0037_alter_chatroom_tutee_alter_chatroom_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
