# Generated by Django 6.0.2 on 2026-05-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0039_wallet_transaction_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('session_credit', 'Session Credit'), ('withdrawal', 'Withdrawal'), ('withdrawal_reversal', 'Withdrawal Reversal'), ('commission_deduction', 'Commission Deduction')], max_length=20),
        ),
    ]
