# Generated by Django 6.0.2 on 2026-05-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0040_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('registration', 'New User Registration'), ('booking_completed', 'Session Completed'), ('institution_added', 'New Institution Request'), ('withdrawal_failed', 'Withdrawal Failure'), ('admin_action', 'Admin Action')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('flagged', 'Flagged')], default='pending', max_length=10),
        ),
    ]
