# Generated by Codex on 2026-05-12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0041_platformactivity_withdrawalrequest_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(
                choices=[
                    ('text', 'Text'),
                    ('system', 'System'),
                    ('booking_event', 'Booking event'),
                ],
                default='text',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
