# Generated by Django 6.0.2 on 2026-05-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0041_platformactivity_withdrawalrequest_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerinstitution',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
