# Generated by Django 6.0.2 on 2026-05-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0042_partnerinstitution_verification_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerinstitution',
            name='verification_status',
        ),
    ]
