# Generated by Django 6.0.2 on 2026-06-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0045_cashout_money_movement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Payment', 'Payment Issue'), ('Booking', 'Booking/No-show'), ('Technical', 'Technical Problem'), ('Dispute', 'Tutee/Tutor Dispute'), ('Other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In_Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('support', 'Support')], default='regular', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_chat_rooms', to='studybuddy.userprofile'),
        ),

        migrations.AddField(
            model_name='supportticket',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='studybuddy.userprofile'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studybuddy.booking'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='chatroom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='studybuddy.chatroom'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studybuddy.transaction'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='studybuddy.userprofile'),
        ),
    ]
