# Generated by Django 6.0.2 on 2026-06-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0045_cashout_money_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by_role',
            field=models.CharField(blank=True, choices=[('tutee', 'Tutee'), ('tutor', 'Tutor')], default='', max_length=10),
        ),
    ]
