# Generated by Django 6.0.2 on 2026-06-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0049_emailotpchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('login_otp', 'Login OTP'), ('password_reset', 'Password reset'), ('password_changed', 'Password changed')], max_length=32)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'purpose', 'created_at'], name='studybuddy__recipie_83df94_idx'), models.Index(fields=['created_at'], name='studybuddy__created_cea3df_idx')],
            },
        ),
    ]
