# Generated by Django 6.0.2 on 2026-06-05 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0049_emailotpchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.ImageField(upload_to='tutor_applications/school_ids/')),
                ('enrollment_proof', models.FileField(upload_to='tutor_applications/enrollment_proofs/')),
                ('reason_to_tutor', models.TextField(blank=True, help_text='Why do you want to become a tutor?')),
                ('application_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='platformactivity',
            name='activity_type',
            field=models.CharField(choices=[('registration', 'New User Registration'), ('booking_completed', 'Session Completed'), ('institution_added', 'New Institution Request'), ('withdrawal_failed', 'Withdrawal Failure'), ('admin_action', 'Admin Action'), ('tutor_application', 'Tutor Application')], max_length=30),
        ),
        migrations.AddField(
            model_name='tutorapplication',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_application', to='studybuddy.userprofile'),
        ),
        migrations.AddField(
            model_name='tutorapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to='studybuddy.userprofile'),
        ),
    ]
