# Generated by Django 6.0.2 on 2026-06-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0050_tutorapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Tutee', 'Tutee'), ('Tutor', 'Tutor'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], max_length=20),
        ),
    ]
