# Generated by Django 6.0.2 on 2026-06-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0050_emailsendlog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notif_recipient_date_idx'),
        ),
    ]
