# Generated by Django 6.0.2 on 2026-06-07 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0050_tutorapplication_and_more'),
        ('studybuddy', '0051_add_notification_recipient_date_index'),
    ]

    operations = [
    ]
