# Generated by Django 6.0.2 on 2026-06-11 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0051_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformactivity',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='studybuddy.partnerinstitution'),
        ),
    ]
