# Generated by Django 6.0.2 on 2026-06-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0052_merge_20260607_1230'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['student', 'status', 'session_date'], name='studybuddy__student_d2f4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tutor', 'status', 'session_date'], name='studybuddy__tutor_i_ebe003_idx'),
        ),
    ]
