# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0053_booking_studybuddy__student_d2f4ac_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dashboard_hidden_by_student_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dashboard_hidden_by_tutor_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
