# Generated by Django 6.0.2 on 2026-06-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0052_platformactivity_institution_and_more'),
        ('studybuddy', '0054_tutorapplication_application_status_idx'),
    ]

    operations = [
    ]
