# Generated by Codex on 2026-07-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0055_merge_20260617_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorDocumentRenewalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.ImageField(upload_to='tutor_applications/renewal_school_ids/')),
                ('enrollment_proof', models.FileField(upload_to='tutor_applications/renewal_enrollment_proofs/')),
                ('reason_to_tutor', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_renewal_reviews', to='studybuddy.tutorapplication')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_renewal_reviews', to='studybuddy.userprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_document_renewals', to='studybuddy.userprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [
                    models.Index(fields=['profile', 'status'], name='studybuddy__profile_71f0af_idx'),
                    models.Index(fields=['application', 'status'], name='studybuddy__applica_1d5f57_idx'),
                    models.Index(fields=['status', 'submitted_at'], name='studybuddy__status_82fcda_idx'),
                ],
            },
        ),
    ]
