# Generated by Django 6.0.2 on 2026-06-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0052_platformactivity_institution_and_more'),
        ('studybuddy', '0056_sessioncheckin'),
    ]

    operations = [
    ]
