# Generated by Codex on 2026-07-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0056_sessioncheckin'),
        ('studybuddy', '0056_tutordocumentrenewalreview'),
    ]

    operations = []
