# Generated by Django 6.0.2 on 2026-06-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0057_merge_20260614_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('session_credit', 'Session Credit'), ('withdrawal', 'Withdrawal'), ('withdrawal_reversal', 'Withdrawal Reversal'), ('cashout_fee', 'Cash-Out Provider Fee'), ('cashout_fee_reversal', 'Cash-Out Provider Fee Reversal'), ('commission_deduction', 'Commission Deduction'), ('cash_in', 'Wallet Top-Up')], max_length=30),
        ),
        migrations.CreateModel(
            name='WalletTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider', models.CharField(default='paymongo', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_ups', to='studybuddy.tutor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
