# Generated by Django 6.0.2 on 2026-07-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0057_merge_recommendation_indexes_document_renewals'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorapplication',
            name='reminder_1day_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorapplication',
            name='reminder_7day_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='TuteeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_to_tutor', models.TextField(blank=True, help_text='Why do you want to become a tutor?')),
                ('application_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_7day_sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reminder_1day_sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('school_id', models.ImageField(upload_to='tutee_applications/school_ids/')),
                ('enrollment_proof', models.FileField(upload_to='tutee_applications/enrollment_proofs/')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutee_application', to='studybuddy.userprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tutee_applications', to='studybuddy.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TuteeDocumentRenewalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_to_tutor', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_id', models.ImageField(upload_to='tutee_applications/renewal_school_ids/')),
                ('enrollment_proof', models.FileField(upload_to='tutee_applications/renewal_enrollment_proofs/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_renewal_reviews', to='studybuddy.tuteeapplication')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutee_document_renewal_reviews', to='studybuddy.userprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tutee_document_renewals', to='studybuddy.userprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['profile', 'status'], name='studybuddy__tutee_pr_stat_idx'), models.Index(fields=['application', 'status'], name='studybuddy__tutee_ap_stat_idx'), models.Index(fields=['status', 'submitted_at'], name='studybuddy__tutee_st_sub_idx')],
            },
        ),
    ]
