# Generated by Django 6.0.2 on 2026-06-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0059_adminaccountrequest_institutionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorpayoutaccount',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='rail',
        ),
    ]
