# Generated by Django 6.0.2 on 2026-06-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0060_remove_cashout_rail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
