# Generated by Django 6.0.2 on 2026-06-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0061_withdrawalrequest_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='receiving_institution_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='receiving_institution_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='receiving_institution_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
