# Generated by Django 6.0.2 on 2026-06-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0062_withdrawalrequest_receiving_institution_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='payout_account',
        ),
        migrations.DeleteModel(
            name='TutorPayoutAccount',
        ),
    ]
