# Generated by Codex on 2026-06-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0063_remove_tutorpayoutaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(
                choices=[
                    ('Open', 'Open'),
                    ('In_Progress', 'In Progress'),
                    ('Escalated', 'Escalated'),
                    ('Resolved', 'Resolved'),
                ],
                default='Open',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='escalation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='escalated_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='escalated_tickets',
                to='studybuddy.userprofile',
            ),
        ),
    ]
