# Generated by Django 6.0.2 on 2026-07-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0059_alter_platformactivity_activity_type'),
        ('studybuddy', '0064_supportticket_escalation'),
    ]

    operations = [
    ]
