# Generated by Django 6.0.2 on 2026-07-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0065_merge_20260702_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsendlog',
            name='purpose',
            field=models.CharField(choices=[('login_otp', 'Login OTP'), ('password_reset', 'Password reset'), ('password_changed', 'Password changed'), ('document_renewal_reminder', 'Document renewal reminder')], max_length=32),
        ),
    ]
