# Generated by Django 6.0.2 on 2026-07-04 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0066_alter_emailsendlog_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='session_load_limit',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
