# Generated by Django 6.0.2 on 2026-07-05 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0067_tutor_session_load_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='owning_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_subjects', to='studybuddy.partnerinstitution'),
        ),
        migrations.CreateModel(
            name='InstitutionCourseCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_catalog_entries', to='studybuddy.course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_entries', to='studybuddy.partnerinstitution')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_catalog_entries', to='studybuddy.subjects')),
            ],
            options={
                'ordering': ['course__course_code', 'subject__subject_code'],
                'unique_together': {('institution', 'course', 'subject')},
            },
        ),
    ]
