# Generated by Django 6.0.2 on 2026-07-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0068_subjects_owning_institution_institutioncoursecatalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformactivity',
            name='activity_type',
            field=models.CharField(choices=[('registration', 'New User Registration'), ('booking_completed', 'Session Completed'), ('institution_added', 'New Institution Request'), ('withdrawal_failed', 'Withdrawal Failure'), ('withdrawal_processed', 'Withdrawal Processed'), ('admin_action', 'Admin Action'), ('tutor_application', 'Tutor Application'), ('tutee_application', 'Tutee Application')], max_length=30),
        ),
    ]
