# Generated by Django 6.0.2 on 2026-07-07 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0070_reactivate_cash_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='studybuddy.subjects'),
        ),
    ]
