# Generated by Django 6.0.2 on 2026-07-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0074_global_subject_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuteeapplication',
            name='reason_to_tutor',
        ),
        migrations.RemoveField(
            model_name='tutorapplication',
            name='reason_to_tutor',
        ),
    ]
