# Generated by Django 6.0.2 on 2026-07-13 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0075_remove_tuteeapplication_reason_to_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='proposed_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_subjects', to='studybuddy.tutorapplication'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='proposed_by_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studybuddy.tutor'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tutor_onboarding_skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
