# Generated by Django 6.0.2 on 2026-07-16

import django.db.models.deletion
from django.db import migrations, models


def reject_pending_bookings_and_notify(apps, schema_editor):
    Booking = apps.get_model('studybuddy', 'Booking')
    Notification = apps.get_model('studybuddy', 'Notification')
    for booking in Booking.objects.filter(status='Pending').iterator():
        booking.status = 'Rejected'
        booking.save(update_fields=['status'])
        Notification.objects.create(
            recipient_id=booking.student_id,
            message='A previous booking request was closed. Please rebook instantly using available slots.',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0076_subjects_proposed_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_born_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='penalized_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_cancellation_tickets', to='studybuddy.userprofile'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='reported_by_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolution_verdict',
            field=models.CharField(blank=True, choices=[('excused', 'Excused'), ('counted', 'Counted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='purpose',
            field=models.CharField(choices=[('login_otp', 'Login OTP'), ('password_reset', 'Password reset'), ('password_changed', 'Password changed'), ('document_renewal_reminder', 'Document renewal reminder'), ('booking_confirmed', 'Booking confirmed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('Payment', 'Payment Issue'), ('Booking', 'Booking/No-show'), ('Technical', 'Technical Problem'), ('Dispute', 'Tutee/Tutor Dispute'), ('Other', 'Other'), ('Late_Cancellation', 'Late Cancellation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('session_credit', 'Session Credit'), ('withdrawal', 'Withdrawal'), ('withdrawal_reversal', 'Withdrawal Reversal'), ('cashout_fee', 'Cash-Out Provider Fee'), ('cashout_fee_reversal', 'Cash-Out Provider Fee Reversal'), ('commission_deduction', 'Commission Deduction'), ('cash_in', 'Wallet Top-Up'), ('counted_strike', 'Counted Strike Penalty')], max_length=30),
        ),
        migrations.RunPython(reject_pending_bookings_and_notify, migrations.RunPython.noop),
    ]
