# Generated by Django 6.0.2 on 2026-07-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0077_instant_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
    ]
