# Generated by Django 6.0.2 on 2026-08-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0079_migrate_to_60min_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tutor',
            name='commission_terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
