# Generated by Django 6.0.2 on 2026-08-10 06:03

from django.db import migrations, models
from django.db.models import Q


def excuse_pre_cutover_strikes(apps, schema_editor):
    """Excuse every unresolved Late Cancellation ticket that exists at cutover.

    Strikes become *provisional* in this release: an unresolved ticket now counts against the
    booking gate on its own, where previously only an explicit `counted` verdict did. Without this
    backfill that change is retroactive -- tutees would be blocked on deploy for cancellations made
    under the old, invisible, calendar-month rule, having never seen a strike count.

    Every row that exists when this runs is by definition pre-cutover, so no timestamp filter is
    needed. Tickets already carrying a verdict are left alone: an admin judged those deliberately.
    """
    SupportTicket = apps.get_model('studybuddy', 'SupportTicket')
    SupportTicket.objects.filter(
        Q(resolution_verdict__isnull=True) | Q(resolution_verdict=''),
        category='Late_Cancellation',
    ).update(resolution_verdict='excused')


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0080_subjects_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['penalized_user', 'category', 'created_at'], name='ticket_strike_window_idx'),
        ),
        # Irreversible by choice: reversing would un-excuse tickets an admin may have excused for
        # real since the cutover, which is indistinguishable from the ones this backfilled.
        migrations.RunPython(excuse_pre_cutover_strikes, migrations.RunPython.noop),
    ]
