# Generated by Django 6.0.2 on 2026-08-19 10:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0082_subjects_department_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('hybrid', 'Hybrid blend'), ('cbf', 'Content-based match components')], max_length=20)),
                ('key', models.CharField(max_length=32)),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='algorithm_weight_updates', to='studybuddy.userprofile')),
            ],
            options={
                'ordering': ['group', 'key'],
                'unique_together': {('group', 'key')},
            },
        ),
    ]
