from django.urls import path, include
from django.conf.urls.static import static
from .views import(
                   cancel_booking,
                   complete_booking,
                   list_courses,
                   login_view, 
                   list_notifications,
                   mark_notification_read,
                   register_user, 
                   submit_session_payment,
                   submit_session_rating,
                   student_dashboard, 
                   SearchTutorsView,
                   SubjectListView, template_availability, tutor_availability, 
                   tutor_confirm_booking,
                   tutor_dashboard,
                    tutor_detail,
                    list_bookings,
                    booking_detail,
                    setup_profile,
                    profile_status,
                    get_tutor_profile
                   )
from .admin_views import (
    AdminAnalyticsExportView,
    AdminCourseCatalogView,
    AdminStatsView, AdminWithdrawalListView, AdminWithdrawalDetailView,
    AdminUserListView, AdminInstitutionView, AdminAnalyticsView,
    AdminUserBookingsView, AdminUserBookingsExportView,
    AdminUserAvailabilityView, AdminUserAvailabilityExportView,
    AdminUserStatsView, AdminUserStatsExportView,
    AdminPendingActionsView, InstitutionRequestView,
    AdminTutorApplicationListView, AdminTutorApplicationDetailView,
    AdminTutorProposedSubjectDetailView,
    AdminTutorDocumentRenewalDetailView, SuperAdminInstitutionPerformanceView,
    AdminTuteeApplicationListView, AdminTuteeApplicationDetailView,
    AdminTuteeDocumentRenewalDetailView, AdminOperationalQueueView,
    AdminUserVerificationDevToolsView
)
from . import views

print("STUDYBUDDY URLS LOADED")

urlpatterns = [
    # Admin Routes
    path('admin/stats/', AdminStatsView.as_view()),
    path('admin/operational-queue/', AdminOperationalQueueView.as_view()),
    path('admin/withdrawals/', AdminWithdrawalListView.as_view()),
    path('admin/withdrawals/<int:pk>/', AdminWithdrawalDetailView.as_view()),
    path('admin/tutor-applications/', AdminTutorApplicationListView.as_view()),
    path('admin/tutor-applications/<int:pk>/', AdminTutorApplicationDetailView.as_view()),
    path(
        'admin/tutor-applications/<int:pk>/subjects/<str:subject_code>/',
        AdminTutorProposedSubjectDetailView.as_view(),
    ),
    path('admin/tutor-document-renewals/<int:pk>/', AdminTutorDocumentRenewalDetailView.as_view()),
    path('admin/tutee-applications/', AdminTuteeApplicationListView.as_view()),
    path('admin/tutee-applications/<int:pk>/', AdminTuteeApplicationDetailView.as_view()),
    path('admin/tutee-document-renewals/<int:pk>/', AdminTuteeDocumentRenewalDetailView.as_view()),
    path('admin/users/', AdminUserListView.as_view()),
    path('admin/users/<int:pk>/', AdminUserListView.as_view()),
    path('admin/users/<int:pk>/bookings/', AdminUserBookingsView.as_view()),
    path('admin/users/<int:pk>/bookings/export/', AdminUserBookingsExportView.as_view()),
    path('admin/users/<int:pk>/availability/', AdminUserAvailabilityView.as_view()),
    path('admin/users/<int:pk>/availability/export/', AdminUserAvailabilityExportView.as_view()),
    path('admin/users/<int:pk>/stats/', AdminUserStatsView.as_view()),
    path('admin/users/<int:pk>/stats/export/', AdminUserStatsExportView.as_view()),
    path('admin/users/<int:pk>/verification-dev-tools/', AdminUserVerificationDevToolsView.as_view()),
    path('admin/course-catalog/', AdminCourseCatalogView.as_view()),
    path('admin/course-catalog/<str:pk>/', AdminCourseCatalogView.as_view()),
    path('admin/institutions/', AdminInstitutionView.as_view()),
    path('admin/institutions/<int:pk>/', AdminInstitutionView.as_view()),
    path('admin/institutions/performance/', SuperAdminInstitutionPerformanceView.as_view()),
    path('admin/analytics/', AdminAnalyticsView.as_view()),
    path('admin/analytics/export/', AdminAnalyticsExportView.as_view()),
    path('admin/pending-actions/', AdminPendingActionsView.as_view()),
    path('admin/institution-requests/', InstitutionRequestView.as_view()),
    path('admin/institution-requests/<int:pk>/', InstitutionRequestView.as_view()),
    path('admin/support/tickets/', views.admin_list_tickets),
    path('admin/support/tickets/<int:ticket_id>/claim/', views.admin_claim_ticket),
    path('admin/support/tickets/<int:ticket_id>/escalate/', views.admin_escalate_ticket),
    path('admin/support/tickets/<int:ticket_id>/resolve/', views.admin_resolve_ticket),

    path('support/tickets/create/', views.create_support_ticket),
    path('support/tickets/my/', views.list_my_tickets),
    path('register/', register_user),
    path('login/', login_view),
    path('login/verify-otp/', views.login_verify_otp),
    path('login/resend-otp/', views.login_resend_otp),
    path('password-reset/request/', views.password_reset_request),
    path('password-reset/confirm/', views.password_reset_confirm),
    path('logout/', views.logout_view),
    # Mode-aware refresh: also returns the profile's current active mode so a client whose mode
    # was changed on another device notices within one refresh cycle.
    path('token/refresh/', views.ModeAwareTokenRefreshView.as_view(), name='token_refresh'),
    path('profile/status/', views.profile_status),
    path('switch-mode/', views.switch_mode),
    path('tutor-application/status/', views.tutor_application_status),
    path('tutor-application/submit/', views.tutor_application_submit),
    path('tutor-application/resubmit/', views.tutor_application_resubmit),
    path('tutor-application/renewal/', views.tutor_document_renewal_submit),
    path('tutee-application/status/', views.tutee_application_status),
    path('tutee-application/resubmit/', views.tutee_application_resubmit),
    path('tutee-application/renewal/', views.tutee_document_renewal_submit),
    path('preferences/', views.save_preferences),
    path('partner-institutions/', views.partner_institutions_list),
    path('dashboard/', student_dashboard),
    path('recommendations/', views.dashboard_recommendations),
    path('tutee/profile/', views.get_tutee_profile),
    path('tutee/profile/avatar/', views.upload_tutee_avatar),
    path('tutee/profile/update/', views.update_tutee_profile),
    path('tutor/profile/', views.get_tutor_profile),
    path('tutor/profile/avatar/', views.upload_tutor_avatar),
    path('tutor/subjects/', views.get_tutor_subjects),
    path('tutor/subjects/add/', views.add_tutor_subject),
    path('tutor/subjects/propose/', views.propose_tutor_subject),
    path('tutor/subjects/update/<str:subject_code>/', views.update_tutor_subject),
    path('tutor/subjects/remove/<str:subject_code>/', views.remove_tutor_subject),
    path('search-tutors/', SearchTutorsView.as_view(), name='search-tutors'),
    path('subjects/',SubjectListView.as_view(), name='subjects'),
    path('courses/', list_courses),
    path('tutor-dashboard/', tutor_dashboard, name='tutor-dashboard'),
    path('tutors/<int:profile_id>/', tutor_detail),
    path('tutors/<int:tutor_id>/availability/', tutor_availability),
    path('profile/setup/', views.setup_profile),
    path('tutor/update/', views.update_tutor_profile),
    path('bookings/', views.list_bookings),
    path('bookings/<int:booking_id>/', views.booking_detail),
    path('payment-methods/', views.payment_methods),
    #Dynamic
    
    path('bookings/confirm/', views.confirm_payment_and_book),
    path('bookings/<int:booking_id>/submit-payment/', submit_session_payment),
    path('bookings/<int:booking_id>/tutor-confirm/', tutor_confirm_booking),
    path('bookings/<int:booking_id>/rating/', submit_session_rating),
    path('bookings/<int:booking_id>/cancel/', cancel_booking),
    path('bookings/<int:booking_id>/venue-confirmation/', views.confirm_session_venue),
    path('bookings/<int:booking_id>/midpoint-check-in/', views.record_midpoint_check_in),
    path('bookings/<int:booking_id>/dashboard-pill/', views.dismiss_dashboard_pill),
    path('template-availability/', template_availability),
    path('template-availability/<int:pk>/', template_availability),
    path('availability-overrides/', views.availability_overrides),
    path('availability-overrides/<int:override_id>/', views.delete_availability_override),
    path('bookings/<int:booking_id>/complete/', complete_booking),
    path('bookings/<uuid:booking_request_id>/location/', views.update_booking_location),
    path('notifications/', list_notifications),
    path('notifications/<int:notification_id>/read/', mark_notification_read),
    path('wallet/', views.wallet_status),
    path('wallet/transactions/', views.wallet_transactions),
    path('wallet/receiving-institutions/', views.receiving_institutions),
    path('wallet/cash-outs/recent/', views.recent_cash_outs),
    path('wallet/cash-outs/', views.cash_outs),
    path('wallet/paymongo/callback/', views.paymongo_cashout_callback),
    path('wallet/withdraw/', views.cash_outs),
    path('wallet/withdrawals/', views.list_withdrawals),
    path('wallet/cash-in/', views.initiate_cash_in),
    path('wallet/cash-in/<int:topup_id>/verify/', views.verify_cash_in),
    path('payments/initiate/', views.initiate_online_payment),
    path('bookings/<int:booking_id>/verify-online-payment/', views.verify_online_payment),
    path('dev/bookings/<int:booking_id>/force-live/', views.dev_force_booking_live),
    path('dev/bookings/<int:booking_id>/clear-force-live/', views.dev_clear_booking_live),
    path(
        'dev/bookings/<int:booking_id>/ready-for-payment/',
        views.dev_mark_booking_ready_for_payment
    ),
    # Dev wallet fund tools (gated in-view by BOOKING_DEV_TOOLS_ENABLED, same as the booking ones above)
    path('dev/wallet/add/', views.dev_add_wallet_funds),
    path('dev/wallet/remove/', views.dev_remove_wallet_funds),
    # Self-service verification dev tools (gated in-view by VERIFICATION_DEV_TOOLS_ENABLED)
    path('dev/verification/', views.dev_verification_readout),
    path('dev/verification/set-state/', views.dev_verification_set_state),
    path('dev/verification/enforcement/', views.dev_verification_set_enforcement),
    # Recommendation algorithm demo tool (gated in-view by ALGORITHM_DEMO_TOOLS_ENABLED + IsSuperAdminUser)
    path('dev/algorithm-demo/tutees/', views.algorithm_demo_search_tutees),
    path('dev/algorithm-demo/recommend/', views.algorithm_demo_recommend),
    path('dev/algorithm-demo/recommend-whatif/', views.algorithm_demo_recommend_whatif),
    path('dev/algorithm-demo/rating/', views.algorithm_demo_update_rating),
    path('tutor/setup/', views.tutor_setup),
    path('tutor/accept-commission-terms/', views.accept_commission_terms),
    path(
        'tutor/onboarding/skip-verification/',
        views.skip_tutor_onboarding_verification,
    ),
    path('recommend-tutors/', views.recommend_tutors_view),
    path('chat/', include('studybuddy.chat.urls')),
]
