"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from dotenv import load_dotenv
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY env var is required but not set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', False)

if not DEBUG:
    # Render (this project's demo/production host) has no outbound IPv6 route at all.
    # Already hit this once for the database (Supabase's direct-connection host is
    # IPv6-only; worked around via the Supavisor pooler -- see DB_HOST/DB_USER below) and
    # again for login OTP email (smtp.gmail.com publishes both A and AAAA records, and the
    # IPv6 attempt fails with "Network is unreachable"). Rather than special-case every
    # outbound host one at a time, force all DNS resolution in this process to IPv4-only.
    # No effect on local dev, which isn't gated by this network limitation.
    import socket

    _original_getaddrinfo = socket.getaddrinfo

    def _ipv4_only_getaddrinfo(host, port, family=0, type=0, proto=0, flags=0):
        return _original_getaddrinfo(host, port, socket.AF_INET, type, proto, flags)

    socket.getaddrinfo = _ipv4_only_getaddrinfo

_allowed_hosts_raw = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(',') if h.strip()]

if DEBUG:
    # Allow local dev + ngrok tunnels when testing from Vite.
    ALLOWED_HOSTS = ["*"]
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_HEADERS = [
        "accept",
        "accept-encoding",
        "authorization",
        "content-type",
        "dnt",
        "origin",
        "user-agent",
        "x-csrftoken",
        "x-requested-with",
        "ngrok-skip-browser-warning",
    ]
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5173",
        "https://*.ngrok-free.dev",
        "https://*.ngrok-free.app",
    ]
else:
    # Production: lock CORS/CSRF to explicitly trusted origins (comma-separated env vars).
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        o.strip() for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()
    ]
    # Optional regex allowlist, for platforms like Vercel that mint a unique per-deployment
    # URL every push -- CORS_ALLOWED_ORIGINS alone can't cover those without editing the env
    # var on every deploy. Empty by default, so real production (which won't set this) is
    # unaffected.
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r.strip() for r in os.getenv('CORS_ALLOWED_ORIGIN_REGEXES', '').split(',') if r.strip()
    ]
    # Explicit defaults plus x-demo-auth, which carries the demo Basic Auth
    # credential (see demo_basic_auth.py) and isn't in django-cors-headers'
    # built-in default list.
    CORS_ALLOW_HEADERS = [
        "accept",
        "accept-encoding",
        "authorization",
        "content-type",
        "dnt",
        "origin",
        "user-agent",
        "x-csrftoken",
        "x-requested-with",
        "x-demo-auth",
    ]
    CSRF_TRUSTED_ORIGINS = [
        o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
    ]

    # Transport / cookie hardening. Behind a TLS-terminating proxy (e.g. ngrok),
    # trust the forwarded-proto header so the SSL redirect doesn't loop.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '240/min',
        'login': '5/min',
        'register': '10/hour',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}
# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'anymail',
    'django_q',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'testapp',
    'studybuddy',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Demo-only shared-password gate (see ADR-0005). Only active when both env vars are
# set, so local dev and real production (which don't set these) are unaffected.
DEMO_BASIC_AUTH_USER = os.getenv('DEMO_BASIC_AUTH_USER', '')
DEMO_BASIC_AUTH_PASSWORD = os.getenv('DEMO_BASIC_AUTH_PASSWORD', '')
if DEMO_BASIC_AUTH_USER and DEMO_BASIC_AUTH_PASSWORD:
    MIDDLEWARE.insert(0, 'studybuddy.demo_basic_auth.DemoBasicAuthMiddleware')

IS_DEMO_DEPLOYMENT = bool(DEMO_BASIC_AUTH_USER and DEMO_BASIC_AUTH_PASSWORD)

# Kill switch for all outbound email. Email suppression used to be implied by
# IS_DEMO_DEPLOYMENT because Render's free tier blocks outbound SMTP (ports 25/465/587)
# and Resend needs a verified domain StudyBuddy does not own. The demo now runs on a paid
# Render instance, which unblocks 465/587, so delivery defaults to ON everywhere and this
# stays only as an explicit opt-out (e.g. if the provider's daily send cap is hit).
# See docs/plans/2026-08-05-enable-demo-email-delivery.md.
EMAIL_DELIVERY_DISABLED = env_bool("EMAIL_DELIVERY_DISABLED", False)

# The login OTP is only skippable when mail cannot be delivered at all.
LOGIN_OTP_DISABLED = EMAIL_DELIVERY_DISABLED

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
        # Supabase's external Postgres endpoint requires SSL; local Postgres does
        # not, so this defaults to libpq's own default ("prefer") and only needs
        # to be set to "require" via DB_SSLMODE for Supabase-backed environments.
        "OPTIONS": {"sslmode": os.getenv("DB_SSLMODE", "prefer")},
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Email
# https://docs.djangoproject.com/en/6.0/topics/email/

EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT") or "587")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
_configured_default_from_email = os.getenv("DEFAULT_FROM_EMAIL", "")
DEFAULT_FROM_EMAIL = _configured_default_from_email or "StudyBuddy <no-reply@localhost>"
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT") or "10")

# Resend (https://resend.com) via django-anymail. Preferred transport when an API key
# is present; falls back to SMTP (legacy) or the console backend (local dev).
RESEND_API_KEY = os.getenv("RESEND_API_KEY", "")
ANYMAIL = {"RESEND_API_KEY": RESEND_API_KEY}
_resend_configured = bool(RESEND_API_KEY and _configured_default_from_email)

_smtp_configured = all([
    EMAIL_HOST,
    EMAIL_HOST_USER,
    EMAIL_HOST_PASSWORD,
    _configured_default_from_email,
])

if _resend_configured:
    EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
elif DEBUG and not _smtp_configured:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
elif not _smtp_configured:
    raise RuntimeError(
        "Email transport not configured when DEBUG=false: set RESEND_API_KEY + "
        "DEFAULT_FROM_EMAIL, or the SMTP env vars "
        "(EMAIL_HOST, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, DEFAULT_FROM_EMAIL)."
    )
else:
    EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")

# Limit upload size to prevent large files from tying up worker threads.
# Files larger than FILE_UPLOAD_MAX_MEMORY_SIZE are streamed to a temp file.
# The hard ceiling (DATA_UPLOAD_MAX_MEMORY_SIZE) is enforced by Django before
# the view code runs.
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB hard ceiling on non-file POST data
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024    # 5 MB — files above this go to temp disk

# Per-file size cap applied to tutor application documents and avatar uploads.
# Mirrored in the frontend as MAX_DOCUMENT_UPLOAD_SIZE_BYTES (src/config.js) — keep in sync.
MAX_DOCUMENT_UPLOAD_SIZE = 5 * 1024 * 1024  # 5 MB

# Tutee enrollment verification booking gate (docs/plans/2026-07-01-tutee-verification-phase2-gate.md).
# Existing tutees get a one-time, global 30-day grace period before new-booking creation is gated on
# their document verification status. Unset by default — a fresh clone/CI run must never start gating
# tutees just because wall-clock time passed some hardcoded date. Set the env var once, to (actual
# rollout date + 30 days), at deploy time.
TUTEE_VERIFICATION_ENFORCEMENT_START_DATE = os.getenv('TUTEE_VERIFICATION_ENFORCEMENT_START_DATE')

# Enables the self-service verification dev panel (state jumper + enforcement override) and the
# SuperAdmin verification dev tools. Defaults False so it is inert in production even if DEBUG is on;
# the dev endpoints check this flag before any work and 403 when it is off.
VERIFICATION_DEV_TOOLS_ENABLED = env_bool('VERIFICATION_DEV_TOOLS_ENABLED', False)

# Enables the staff-only recommendation algorithm demo endpoints (score breakdown for the live
# panel demo tool). Defaults False so it is inert in production; the endpoints check this flag
# before any work and 403 when it is off.
ALGORITHM_DEMO_TOOLS_ENABLED = env_bool('ALGORITHM_DEMO_TOOLS_ENABLED', False)

# Enables the dev booking/wallet tools (force a booking's session into a given live phase, mark
# ready-for-payment, credit/debit a tutor wallet). Previously gated on DEBUG alone, which meant
# they were unreachable on the demo deployment (DEBUG=False there by design). Defaults False so
# real production stays inert; the demo sets this explicitly to let the panel force session/wallet
# states for the thesis defense.
BOOKING_DEV_TOOLS_ENABLED = env_bool('BOOKING_DEV_TOOLS_ENABLED', False)

# Surfaces the login OTP code in the API response and the "Check Your Email" screen, so demo/test
# accounts can be logged into without access to their inbox. Previously gated on DEBUG alone, which
# meant it was unreachable on the demo deployment (DEBUG=False there by design). Defaults False so
# real production never leaks OTP codes; the demo sets this explicitly.
OTP_DEBUG_CODE_ENABLED = env_bool('OTP_DEBUG_CODE_ENABLED', False)

# Includes the raw PayMongo error body (provider_status/provider_error) in payment failure
# responses. Previously gated on DEBUG alone, which meant it was unreachable on the demo
# deployment. Defaults False so real production never echoes provider error payloads to
# clients; the demo sets this explicitly to help diagnose sandbox payment failures live.
PAYMONGO_DEBUG_ERRORS_ENABLED = env_bool('PAYMONGO_DEBUG_ERRORS_ENABLED', False)

PASSWORD_RESET_TIMEOUT = 3600
LOGIN_OTP_TTL_SECONDS = 600
LOGIN_OTP_MAX_ATTEMPTS = 5

# Email resilience tuning (used by studybuddy.mailer)
# OTP is sent synchronously on the login critical path, so keep its timeout short
# and retry only a couple of times before failing honestly back to the user.
EMAIL_SYNC_TIMEOUT = int(os.getenv("EMAIL_SYNC_TIMEOUT") or "6")
# Sync OTP path fails fast (fewer attempts) so a provider outage can't stall login
# much past the original ~10s ceiling and exhaust the request/worker pool.
EMAIL_SYNC_MAX_ATTEMPTS = int(os.getenv("EMAIL_SYNC_MAX_ATTEMPTS") or "2")
# Async path (Q_CLUSTER) has no one waiting, so it tolerates more retries.
EMAIL_SEND_MAX_ATTEMPTS = int(os.getenv("EMAIL_SEND_MAX_ATTEMPTS") or "3")
EMAIL_SEND_RETRY_BACKOFF = float(os.getenv("EMAIL_SEND_RETRY_BACKOFF") or "0.5")
# Per-recipient send cap (defence on top of the per-IP throttle) to protect the
# provider's daily quota from a single abused address.
EMAIL_SEND_CAP_PER_HOUR = int(os.getenv("EMAIL_SEND_CAP_PER_HOUR") or "10")


# Django-Q2 background task queue. Uses the existing database as the broker (ORM
# broker) so no Redis/extra service is required. Run the worker with
# `python manage.py qcluster`. Async email (password reset / notices) is dispatched
# here; login OTP stays synchronous by design.
Q_CLUSTER = {
    "name": "studybuddy",
    "orm": "default",
    "workers": int(os.getenv("Q_WORKERS") or "2"),
    "timeout": 60,
    "retry": 120,
    "max_attempts": EMAIL_SEND_MAX_ATTEMPTS,
    "save_limit": 250,
    "catch_up": False,
    "label": "Django Q",
}

import sys
if 'test' in sys.argv:
    Q_CLUSTER["sync"] = True

# Cache backend. Redis when REDIS_URL is set (preferred: fast and shared across
# worker processes — required for correct invalidation in multi-worker prod).
# Without REDIS_URL we fall back to a per-process in-memory cache so local dev and
# CI run without a Redis server (degraded: not shared across processes).
REDIS_URL = os.getenv("REDIS_URL", "")

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
# Defaults to the project-local folder for dev. In production (Render), set MEDIA_ROOT
# to the mount path of an attached persistent Disk -- Render's web service filesystem is
# otherwise ephemeral and wipes uploaded avatars/documents on every deploy or restart.
MEDIA_ROOT = os.getenv('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

ASGI_APPLICATION = 'backend.asgi.application'

# Use Redis in production (set REDIS_URL); in-memory only works for a single process.
_redis_url = os.getenv('REDIS_URL')
if _redis_url:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [_redis_url]},
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# PayMongo & Integration Settings
PAYMONGO_SECRET_KEY = os.getenv("PAYMONGO_SECRET_KEY")
if not PAYMONGO_SECRET_KEY:
    raise RuntimeError("PAYMONGO_SECRET_KEY env var is required but not set")
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")
PAYMONGO_WALLET_ID = os.getenv("PAYMONGO_WALLET_ID", "")
PAYMONGO_CASHOUT_CALLBACK_URL = os.getenv("PAYMONGO_CASHOUT_CALLBACK_URL", "")
# Shared secret appended to the cashout callback URL and verified on the inbound
# callback. When set, callbacks without a matching ?token= are rejected.
PAYMONGO_CASHOUT_CALLBACK_SECRET = os.getenv("PAYMONGO_CASHOUT_CALLBACK_SECRET", "")
# Dev-only: simulate a successful PayMongo wallet transaction instead of calling the
# live Money Movement API. PayMongo test mode has no payouts product, so this is the
# only way to exercise cash-out locally or in the demo environment (see ADR-0003).
# Gated on the secret key's own mode (sk_live_ vs sk_test_) rather than DEBUG, since
# the demo runs with DEBUG=False but still needs mock cash-outs on a sandbox key.
PAYMONGO_CASHOUT_MOCK = os.getenv("PAYMONGO_CASHOUT_MOCK", "false").lower() in ("1", "true", "yes")
PAYMONGO_LIVE_MODE = PAYMONGO_SECRET_KEY.startswith("sk_live_")
if PAYMONGO_CASHOUT_MOCK and PAYMONGO_LIVE_MODE:
    raise RuntimeError(
        "PAYMONGO_CASHOUT_MOCK cannot be enabled alongside a live PayMongo secret key "
        "(sk_live_...). This would fake cash-out payouts while real money could be "
        "moving elsewhere in the same environment."
    )
if not DEBUG and not PAYMONGO_CASHOUT_CALLBACK_SECRET:
    raise RuntimeError(
        "PAYMONGO_CASHOUT_CALLBACK_SECRET env var is required when DEBUG=false."
    )
CASHOUT_PROVIDER_FEE_PHP = os.getenv("CASHOUT_PROVIDER_FEE_PHP", "10")
CASHIN_MIN_PHP = os.getenv("CASHIN_MIN_PHP", "50")
CASHOUT_MIN_PHP = os.getenv("CASHOUT_MIN_PHP", "50")
# InstaPay's real per-transaction cap (see ADR-0001) -- every cash-out uses InstaPay now.
CASHOUT_MAX_PHP = os.getenv("CASHOUT_MAX_PHP", "50000")

# Logging. Without this, Django falls back to Python's "handler of last resort", which prints
# only the bare message for unhandled exceptions (e.g. "Internal Server Error: /api/login/")
# and drops the traceback entirely -- exactly what made the OTP email bug hard to diagnose from
# Render's console. This sends full tracebacks (via exc_info) to stdout/stderr, which Render
# captures as log output, so no separate log aggregator is needed for the demo.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
    "loggers": {
        # Explicit entry so request-handling exceptions (unhandled 500s) always print with
        # their traceback, regardless of the root logger's level.
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
