# -*- coding: utf-8 -*-
"""The 35 table blocks for the thesis Database Structure section.

Every field is transcribed from backend/studybuddy/models.py,
backend/studybuddy/chat/models.py and backend/backend/settings.py.

Block shape:
    name        -> "Table Name:" value
    pk          -> "Primary Key:" value
    fks         -> list of strings; one line each when >1, inline when 1, "--" when empty
    unique      -> "Unique Constraint:" value, or None to omit the line
    desc        -> description paragraph
    rows        -> list of (field_name, type, description)
"""

BLOCKS = [
    # ---------------- 1. Identity and authentication ----------------
    dict(
        name="auth_users (django built in)",
        pk="id",
        fks=[],
        unique="username is unique",
        desc="This table stores authentication credentials and login-related information of all "
             "users in the system. It is automatically generated by Django's built-in "
             "authentication framework.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("username", "Varchar(150)", "Unique login handle; the email address is stored here"),
            ("password", "Varchar(128)", "Password hashed with PBKDF2-SHA256"),
            ("first_name", "Varchar(150)", "Django default first name"),
            ("last_name", "Varchar(150)", "Django default last name"),
            ("email", "Varchar(254)", "User email address"),
            ("is_staff", "Boolean", "Grants access to the Django admin panel"),
            ("is_active", "Boolean", "Indicates if the account is active"),
            ("is_superuser", "Boolean", "Superuser privilege flag"),
            ("last_login", "Datetime", "Last login timestamp"),
            ("date_joined", "Datetime", "Account creation date"),
        ],
    ),
    dict(
        name="token_blacklist_outstandingtoken (SimpleJWT built in)",
        pk="id",
        fks=["user -> auth_users"],
        unique="jti is unique",
        desc="This table records every refresh token issued by the system so that a token can "
             "later be revoked. It is generated by the SimpleJWT token_blacklist application and "
             "supports the logout and session-invalidation flow.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("user", "FK", "User the refresh token was issued to"),
            ("jti", "Varchar(255)", "Unique JWT identifier for the token"),
            ("token", "Text", "The encoded refresh token"),
            ("created_at", "Datetime", "Time the token was issued"),
            ("expires_at", "Datetime", "Time the token stops being valid"),
        ],
    ),
    dict(
        name="token_blacklist_blacklistedtoken (SimpleJWT built in)",
        pk="id",
        fks=["token -> token_blacklist_outstandingtoken"],
        unique="token is unique (one blacklist entry per outstanding token)",
        desc="This table marks refresh tokens that have been revoked. A token listed here is "
             "rejected on any further refresh attempt, which is how the system enforces logout "
             "and forced sign-out.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("token", "FK", "The outstanding token being revoked"),
            ("blacklisted_at", "Datetime", "Time the token was revoked"),
        ],
    ),
    dict(
        name="email_otp_challenge",
        pk="id",
        fks=["user -> auth_users"],
        unique="challenge_id is unique",
        desc="This table stores the one-time passcodes emailed to users during login. It holds "
             "only a hash of the code, together with the expiry, attempt and resend counters used "
             "to rate-limit verification.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("user", "FK", "User the challenge was issued to"),
            ("challenge_id", "UUID", "Public identifier returned to the client"),
            ("purpose", "Varchar(20)", "Purpose of the challenge (login)"),
            ("code_hash", "Varchar(64)", "Hash of the one-time passcode"),
            ("expires_at", "Datetime", "Time the code stops being valid"),
            ("consumed_at", "Datetime", "Time the code was successfully used"),
            ("attempt_count", "Int", "Number of verification attempts made"),
            ("resend_count", "Int", "Number of times the code was resent"),
            ("created_at", "Datetime", "Challenge creation timestamp"),
        ],
    ),
    dict(
        name="partner_institution",
        pk="id",
        fks=[],
        unique="school_email_domain is unique",
        desc="This table stores the schools partnered with the platform. The email domain "
             "recorded here is what restricts registration to verified institutional accounts.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("institution_name", "Varchar(255)", "Name of the partner institution"),
            ("school_email_domain", "Varchar(255)", "Email domain that grants access (e.g. cpu.edu.ph)"),
            ("is_active", "Boolean", "Indicates if the partnership is currently active"),
            ("contact_person", "Varchar(255)", "Institutional contact person"),
            ("date_added", "Datetime", "Time the institution was added"),
        ],
    ),
    dict(
        name="institution_request",
        pk="id",
        fks=["reviewed_by -> auth_users"],
        unique=None,
        desc="This table stores applications from schools asking to join the platform. A Super "
             "Admin reviews each request before the institution becomes a partner.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("institution_name", "Varchar(200)", "Name of the requesting institution"),
            ("school_email_domain", "Varchar(100)", "Proposed email domain"),
            ("contact_person", "Varchar(200)", "Name of the requesting contact"),
            ("contact_email", "Varchar(254)", "Email address of the requesting contact"),
            ("note", "Text", "Optional message from the requester"),
            ("status", "Varchar(20)", "Pending / Approved / Rejected"),
            ("reviewed_by", "FK", "Super Admin who reviewed the request"),
            ("created_at", "Datetime", "Request submission timestamp"),
            ("reviewed_at", "Datetime", "Time the request was reviewed"),
        ],
    ),
    dict(
        name="user_profile",
        pk="id",
        fks=[
            "user -> auth_users",
            "course -> course",
            "institution -> partner_institution",
        ],
        unique="user is unique (one profile per account)",
        desc="This table stores extended user information beyond Django authentication. It is the "
             "central model of the system, holding personal details, academic information, "
             "institutional affiliation and role designation.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("user", "FK", "References the authentication user"),
            ("fname", "Varchar(100)", "First name"),
            ("mname", "Varchar(100)", "Middle name"),
            ("lname", "Varchar(100)", "Last name"),
            ("course", "FK", "Course the user belongs to"),
            ("year_level", "Int", "Current year level of the student"),
            ("bio", "Text", "Short biography"),
            ("profile_completed", "Boolean", "Indicates if profile setup is complete"),
            ("is_suspended", "Boolean", "Indicates if the account has been suspended by an admin"),
            ("profile_picture", "Image", "User profile picture"),
            ("institution", "FK", "Partner institution the user belongs to"),
            ("is_domain_exempt", "Boolean", "Allows registration outside a partner email domain"),
            ("tutor_onboarding_skipped_at", "Datetime", "Time the user dismissed the tutor onboarding prompt"),
            ("role", "Varchar(20)", "Tutee / Tutor / SuperAdmin"),
            ("created_at", "Datetime", "Profile creation timestamp"),
            ("updated_at", "Datetime", "Last update timestamp"),
        ],
    ),

    # ---------------- 2. Academic taxonomy ----------------
    dict(
        name="strand",
        pk="strand_code",
        fks=[],
        unique=None,
        desc="This table stores academic strands that categorize different educational tracks "
             "such as STEM, ABM, and HUMSS.",
        rows=[
            ("strand_code", "Varchar(10) (PK)", "Unique code for the strand"),
            ("strand_name", "Varchar(100)", "Name of the strand"),
        ],
    ),
    dict(
        name="course",
        pk="course_code",
        fks=["strand -> strand"],
        unique=None,
        desc="This table stores courses offered in the system and associates them with their "
             "respective academic strands.",
        rows=[
            ("course_code", "Varchar(20) (PK)", "Unique identifier for a course"),
            ("course_name", "Varchar(100)", "Full name of the course"),
            ("strand", "FK", "References the strand the course belongs to"),
        ],
    ),
    dict(
        name="subjects",
        pk="subject_code",
        fks=[
            "proposed_by_tutor -> tutor",
            "proposed_application -> tutor_application",
        ],
        unique=None,
        desc="This table stores the subjects available for tutoring on the platform. Subjects may "
             "also be proposed by a tutor during application, in which case they stay pending "
             "until an admin approves them. The keywords column supplies the text used by the "
             "attribute-based matching component of the recommendation engine.",
        rows=[
            ("subject_code", "Varchar(20) (PK)", "Unique subject code"),
            ("subject_name", "Varchar(100)", "Subject name"),
            ("department", "Varchar(100)", "Department offering the subject"),
            ("category", "Varchar(100)", "Broad grouping used for browsing and filtering"),
            ("keywords", "Text", "Search terms used by the recommendation engine"),
            ("status", "Varchar(20)", "Approved / Pending"),
            ("proposed_by_tutor", "FK", "Tutor who proposed the subject, if any"),
            ("proposed_application", "FK", "Tutor application the proposal came from"),
        ],
    ),

    # ---------------- 3. Tutor profile ----------------
    dict(
        name="tutor",
        pk="profile_id",
        fks=[
            "profile -> user_profile",
            "pinned_review -> rating",
        ],
        unique="profile is the primary key (one tutor record per profile)",
        desc="This table stores tutor-specific information extending the user profile. A tutor "
             "account is an extension of an existing tutee profile rather than a separate "
             "account, which is why the profile reference is also the primary key.",
        rows=[
            ("profile", "FK (PK)", "References the user profile"),
            ("teaching_level", "Varchar(100)", "Level the tutor can teach"),
            ("can_online", "Boolean", "Indicates online session capability"),
            ("can_f2f", "Boolean", "Indicates face-to-face capability"),
            ("rating_average", "Float", "Average tutor rating"),
            ("hourly_rate", "Decimal(8,2)", "Tutor's hourly rate"),
            ("response_time", "Varchar(30)", "Within 1 hour / Within a few hours / Within a day"),
            ("response_time_label", "Varchar(50)", "Display text derived from response_time"),
            ("pinned_review", "FK", "Review the tutor chose to feature on their profile"),
            ("total_sessions", "Int", "Total tutoring sessions completed"),
            ("session_load_limit", "Int", "Maximum concurrent accepted sessions (1-20, default 10)"),
            ("created_at", "Datetime", "Tutor record creation date"),
        ],
    ),
    dict(
        name="tutor_subjects",
        pk="id",
        fks=[
            "tutor -> tutor",
            "subject -> subjects",
        ],
        unique=None,
        desc="This junction table links tutors to the subjects they teach and stores expertise "
             "levels. It supplies the tutor-side attribute vector used by the Attribute-Based "
             "Knowledge Filtering component.",
        rows=[
            ("id", "Int (PK)", "Auto-generated identifier"),
            ("tutor", "FK", "Tutor who teaches the subject"),
            ("subject", "FK", "Subject taught by the tutor"),
            ("expertise_level", "Int", "Level of expertise of the tutor in the subject"),
            ("description", "Text", "Tutor's notes on how they teach the subject"),
        ],
    ),
    dict(
        name="preference",
        pk="id",
        fks=["user -> user_profile"],
        unique="user is unique (one preference record per profile)",
        desc="This table stores a tutee's learning preferences captured during onboarding. It "
             "supplies the tutee-side attribute vector used by the Attribute-Based Knowledge "
             "Filtering component.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("user", "FK", "User whose preferences are stored"),
            ("created_at", "Datetime", "Preference creation timestamp"),
        ],
    ),
    dict(
        name="preference_subjects (Many-to-Many Bridge)",
        pk="id",
        fks=[
            "preference -> preference",
            "subjects -> subjects",
        ],
        unique="(preference, subjects) must be unique",
        desc="This table links user preferences with selected subjects. It is generated "
             "automatically by Django for the many-to-many relationship between preference and "
             "subjects.",
        rows=[
            ("id", "Int (PK)", "Auto-generated identifier"),
            ("preference", "FK", "Preference record"),
            ("subjects", "FK", "Subject selected by the user"),
        ],
    ),

    # ---------------- 4. Scheduling ----------------
    dict(
        name="tutor_availability",
        pk="id",
        fks=["tutor -> tutor"],
        unique="(tutor, day, time_slot) must be unique",
        desc="This table stores the recurring weekly schedule a tutor makes available for "
             "tutoring sessions. Each row is a one-hour slot on a given weekday.",
        rows=[
            ("id", "Int (PK)", "Auto-generated identifier"),
            ("tutor", "FK", "Tutor who owns the availability slot"),
            ("day", "Varchar(3)", "Mon / Tue / Wed / Thu / Fri / Sat / Sun"),
            ("time_slot", "Time", "Start time of the available slot"),
            ("is_active", "Boolean", "Indicates if the tutor has enabled the slot"),
            ("is_booked", "Boolean", "Indicates if the system has booked the slot"),
            ("created_at", "Datetime", "Time the slot was created"),
        ],
    ),
    dict(
        name="tutor_availability_override",
        pk="id",
        fks=[
            "tutor -> tutor",
            "availability -> tutor_availability",
        ],
        unique="(tutor, override_date) unique for full-day overrides; "
               "(tutor, override_date, availability) unique for single-slot overrides",
        desc="This table stores one-off exceptions to a tutor's recurring weekly schedule, used "
             "when a tutor is unavailable on a specific date. An override may cancel a single "
             "slot or an entire day.",
        rows=[
            ("id", "Int (PK)", "Auto-generated identifier"),
            ("tutor", "FK", "Tutor the override applies to"),
            ("override_date", "Date", "Calendar date the override applies to"),
            ("availability", "FK", "Specific slot being overridden; empty for a full-day override"),
            ("is_full_day", "Boolean", "Indicates the whole day is unavailable"),
            ("created_at", "Datetime", "Override creation timestamp"),
            ("updated_at", "Datetime", "Last update timestamp"),
        ],
    ),

    # ---------------- 5. Bookings and sessions ----------------
    dict(
        name="booking",
        pk="id",
        fks=[
            "student -> user_profile",
            "tutor -> tutor",
            "availability -> tutor_availability",
            "subject -> subjects",
        ],
        unique="(availability, session_date) must be unique across the Pending, Confirmed, "
               "Awaiting Payment Verification and Completed statuses, which is what prevents "
               "double-booking of the same slot on the same date",
        desc="This table stores tutoring session bookings between students and tutors. It is the "
             "center of the scheduling module: the unique constraint stated above enforces that a "
             "given availability slot can hold only one live booking per date, and the grouping "
             "identifiers allow a multi-slot booking to be treated as a single session.",
        rows=[
            ("id", "Int (PK)", "Auto-generated booking ID"),
            ("student", "FK", "Student who booked the session"),
            ("tutor", "FK", "Tutor assigned for the session"),
            ("availability", "FK", "Selected availability slot"),
            ("subject", "FK", "Subject the session covers"),
            ("session_date", "Date", "Scheduled session date"),
            ("session_mode", "Varchar(10)", "Online / F2F"),
            ("preferred_location", "Varchar(255)", "Meeting place for face-to-face sessions"),
            ("session_group_id", "UUID", "Groups consecutive slots into one session"),
            ("booking_request_id", "UUID", "Groups slots submitted in one booking request"),
            ("status", "Varchar(40)", "Pending / Confirmed / Awaiting Payment Verification / "
                                      "Completed / Rejected / Cancelled"),
            ("cancellation_reason", "Text", "Reason given when the booking was cancelled"),
            ("cancelled_by_role", "Varchar(10)", "Tutee / Tutor"),
            ("meeting_link", "Varchar(200)", "Video call link for online sessions"),
            ("is_born_late", "Boolean", "Marks a booking created inside the late-cancellation window"),
            ("tutee_confirmed", "Boolean", "Tutee confirmed the session took place"),
            ("tutor_confirmed", "Boolean", "Tutor confirmed the session took place"),
            ("dashboard_hidden_by_student_at", "Datetime", "Time the tutee dismissed it from their dashboard"),
            ("dashboard_hidden_by_tutor_at", "Datetime", "Time the tutor dismissed it from their dashboard"),
            ("created_at", "Datetime", "Booking creation date"),
        ],
    ),
    dict(
        name="session_check_in",
        pk="id",
        fks=["booking -> booking"],
        unique="(booking, event_type) must be unique, so each prompt is answered once per booking",
        desc="This table records the in-session prompts answered by participants: a venue "
             "confirmation at the start and a check-in at the midpoint. The responses give the "
             "platform evidence that a session actually took place.",
        rows=[
            ("id", "Int (PK)", "Auto-generated identifier"),
            ("booking", "FK", "Booking the check-in belongs to"),
            ("event_type", "Varchar(30)", "Venue confirmation / Mid-session check-in"),
            ("response", "Varchar(30)", "Yes / No / Good / Having issues"),
            ("responded_at", "Datetime", "Time the prompt was answered"),
        ],
    ),
    dict(
        name="rating",
        pk="id",
        fks=[
            "booking -> booking",
            "student -> user_profile",
            "tutor -> tutor",
        ],
        unique="booking is unique (one rating per booking)",
        desc="This table stores feedback and ratings given by students after tutoring sessions. "
             "It is the source of the historical interaction data consumed by the User-User "
             "Collaborative Filtering component.",
        rows=[
            ("id", "Int (PK)", "Auto-generated rating ID"),
            ("booking", "FK", "Associated booking"),
            ("student", "FK", "Student who gave the rating"),
            ("tutor", "FK", "Tutor being rated"),
            ("rating_score", "Int", "Rating value (1-5)"),
            ("comment", "Text", "Optional feedback"),
            ("created_at", "Datetime", "Rating creation time"),
        ],
    ),

    # ---------------- 6. Payments and wallet ----------------
    dict(
        name="payment_method",
        pk="method_id",
        fks=[],
        unique="code is unique",
        desc="This table stores the available payment methods supported by the system.",
        rows=[
            ("method_id", "Int (PK)", "Unique payment method identifier"),
            ("code", "Varchar(20)", "CASH / GCASH / BANK / online"),
            ("method_name", "Varchar(50)", "Display name of the payment method"),
            ("is_active", "Boolean", "Indicates if the payment method is available"),
            ("created_at", "Datetime", "Creation timestamp"),
        ],
    ),
    dict(
        name="payment",
        pk="id",
        fks=[
            "booking -> booking",
            "method -> payment_method",
        ],
        unique="booking is unique (one payment per booking)",
        desc="This table records payment transactions for tutoring session bookings, including "
             "the uploaded proof of payment used when a tutor verifies that a tutee has paid.",
        rows=[
            ("id", "Int (PK)", "Auto-generated payment ID"),
            ("booking", "FK", "Booking associated with the payment"),
            ("method", "FK", "Payment method used"),
            ("amount", "Decimal(10,2)", "Payment amount"),
            ("payment_status", "Varchar(10)", "Pending / Paid / Failed / Refunded"),
            ("transaction_reference", "Varchar(100)", "Payment reference number"),
            ("receipt_image", "Image", "Uploaded proof of payment"),
            ("paid_at", "Datetime", "Payment completion time"),
            ("created_at", "Datetime", "Payment creation timestamp"),
        ],
    ),
    dict(
        name="wallet",
        pk="id",
        fks=["tutor -> tutor"],
        unique="tutor is unique (one wallet per tutor)",
        desc="This table stores the in-platform wallet balance of each tutor. A wallet row is "
             "created automatically whenever a tutor record is created.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("tutor", "FK", "Tutor who owns the wallet"),
            ("balance", "Decimal(10,2)", "Amount available for withdrawal"),
            ("pending_amount", "Decimal(10,2)", "Amount held against in-flight withdrawals"),
            ("last_updated", "Datetime", "Time the balance last changed"),
        ],
    ),
    dict(
        name="transaction",
        pk="id",
        fks=["wallet -> wallet"],
        unique=None,
        desc="This table is the wallet ledger. Every credit and debit applied to a tutor's wallet "
             "is written here, giving an auditable history behind the reporting and analytics "
             "module.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("wallet", "FK", "Wallet the entry belongs to"),
            ("transaction_type", "Varchar(30)", "Session Credit / Withdrawal / Withdrawal Reversal / "
                                                "Cash-Out Provider Fee / Cash-Out Provider Fee Reversal / "
                                                "Commission Deduction / Wallet Top-Up / Counted Strike Penalty"),
            ("amount", "Decimal(10,2)", "Signed amount applied to the balance"),
            ("description", "Text", "Human-readable explanation of the entry"),
            ("reference_id", "Varchar(100)", "Identifier of the booking or payout that caused it"),
            ("created_at", "Datetime", "Time the entry was recorded"),
        ],
    ),
    dict(
        name="withdrawal_request",
        pk="id",
        fks=["tutor -> tutor"],
        unique=None,
        desc="This table stores tutor requests to cash out their wallet balance, together with "
             "the payout provider's response. The provider columns record what the external "
             "disbursement service returned so a failed payout can be reconciled and reversed.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("tutor", "FK", "Tutor requesting the withdrawal"),
            ("amount", "Decimal(10,2)", "Amount requested"),
            ("method", "Varchar(10)", "GCash / Bank Transfer"),
            ("receiving_institution_id", "Varchar(100)", "Provider identifier of the receiving institution"),
            ("receiving_institution_name", "Varchar(150)", "Name of the receiving institution"),
            ("receiving_institution_code", "Varchar(50)", "Code of the receiving institution"),
            ("account_number", "Varchar(50)", "Destination account number"),
            ("account_name", "Varchar(100)", "Destination account holder name"),
            ("bank_name", "Varchar(100)", "Destination bank name"),
            ("status", "Varchar(10)", "Pending / Processed / Rejected / Failed / Flagged"),
            ("failure_reason", "Text", "Reason recorded when the payout failed"),
            ("provider", "Varchar(30)", "External disbursement provider used"),
            ("provider_wallet_transaction_id", "Varchar(120)", "Provider's transaction identifier"),
            ("provider_reference_number", "Varchar(120)", "Provider's reference number"),
            ("provider_status", "Varchar(30)", "Status string returned by the provider"),
            ("provider_error_code", "Varchar(120)", "Error code returned by the provider"),
            ("provider_error_message", "Text", "Error message returned by the provider"),
            ("provider_fee", "Decimal(10,2)", "Fee charged by the provider"),
            ("net_amount", "Decimal(10,2)", "Amount received after the provider fee"),
            ("callback_received_at", "Datetime", "Time the provider callback arrived"),
            ("requested_at", "Datetime", "Time the withdrawal was requested"),
            ("processed_at", "Datetime", "Time the withdrawal was settled"),
            ("note", "Text", "Admin note attached to the request"),
        ],
    ),
    dict(
        name="wallet_top_up",
        pk="id",
        fks=["tutor -> tutor"],
        unique=None,
        desc="This table stores tutor top-ups that add funds to a wallet. A top-up is needed when "
             "a tutor has collected cash in person and owes the platform its commission.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("tutor", "FK", "Tutor adding funds"),
            ("amount", "Decimal(10,2)", "Amount to be added"),
            ("status", "Varchar(20)", "Pending / Paid / Failed"),
            ("provider", "Varchar(20)", "Payment provider handling the top-up"),
            ("provider_reference", "Varchar(100)", "Provider's reference for the payment"),
            ("created_at", "Datetime", "Top-up creation timestamp"),
            ("paid_at", "Datetime", "Time the payment cleared"),
        ],
    ),

    # ---------------- 7. Verification ----------------
    dict(
        name="tutor_application",
        pk="id",
        fks=[
            "profile -> user_profile",
            "reviewed_by -> user_profile",
        ],
        unique="profile is unique (one tutor application per profile)",
        desc="This table stores the documents a user submits when applying to become a tutor, "
             "along with the admin's review outcome. Approval is what makes a tutor eligible to "
             "receive bookings.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("profile", "FK", "Profile that submitted the application"),
            ("school_id", "Image", "Uploaded school identification card"),
            ("enrollment_proof", "File", "Uploaded proof of enrollment"),
            ("reviewed_by", "FK", "Admin who reviewed the application"),
            ("application_status", "Varchar(20)", "Pending Review / Approved / Rejected"),
            ("rejection_reason", "Text", "Reason given when the application was rejected"),
            ("reviewed_at", "Datetime", "Time the application was reviewed"),
            ("submitted_at", "Datetime", "Application submission timestamp"),
            ("updated_at", "Datetime", "Last update timestamp"),
            ("reminder_7day_sent_at", "Datetime", "Time the 7-day renewal reminder was emailed"),
            ("reminder_1day_sent_at", "Datetime", "Time the 1-day renewal reminder was emailed"),
        ],
    ),
    dict(
        name="tutor_document_renewal_review",
        pk="id",
        fks=[
            "application -> tutor_application",
            "profile -> user_profile",
            "reviewed_by -> user_profile",
        ],
        unique=None,
        desc="This table stores each re-submission of a tutor's verification documents. Documents "
             "must be renewed every 90 days, and every renewal attempt is reviewed and recorded "
             "here separately from the original application.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("application", "FK", "Tutor application being renewed"),
            ("profile", "FK", "Profile submitting the renewal"),
            ("school_id", "Image", "Re-uploaded school identification card"),
            ("enrollment_proof", "File", "Re-uploaded proof of enrollment"),
            ("reviewed_by", "FK", "Admin who reviewed the renewal"),
            ("reason_to_tutor", "Text", "Message shown to the tutor about the renewal"),
            ("status", "Varchar(20)", "Pending Review / Approved / Rejected"),
            ("rejection_reason", "Text", "Reason given when the renewal was rejected"),
            ("reviewed_at", "Datetime", "Time the renewal was reviewed"),
            ("submitted_at", "Datetime", "Renewal submission timestamp"),
            ("updated_at", "Datetime", "Last update timestamp"),
        ],
    ),
    dict(
        name="tutee_application",
        pk="id",
        fks=[
            "profile -> user_profile",
            "reviewed_by -> user_profile",
        ],
        unique="profile is unique (one tutee application per profile)",
        desc="This table stores the documents a student submits to have their tutee account "
             "verified, along with the admin's review outcome. It mirrors the tutor application "
             "table because both roles require institutional verification.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("profile", "FK", "Profile that submitted the application"),
            ("school_id", "Image", "Uploaded school identification card"),
            ("enrollment_proof", "File", "Uploaded proof of enrollment"),
            ("reviewed_by", "FK", "Admin who reviewed the application"),
            ("application_status", "Varchar(20)", "Pending Review / Approved / Rejected"),
            ("rejection_reason", "Text", "Reason given when the application was rejected"),
            ("reviewed_at", "Datetime", "Time the application was reviewed"),
            ("submitted_at", "Datetime", "Application submission timestamp"),
            ("updated_at", "Datetime", "Last update timestamp"),
            ("reminder_7day_sent_at", "Datetime", "Time the 7-day renewal reminder was emailed"),
            ("reminder_1day_sent_at", "Datetime", "Time the 1-day renewal reminder was emailed"),
        ],
    ),
    dict(
        name="tutee_document_renewal_review",
        pk="id",
        fks=[
            "application -> tutee_application",
            "profile -> user_profile",
            "reviewed_by -> user_profile",
        ],
        unique=None,
        desc="This table stores each re-submission of a tutee's verification documents, reviewed "
             "on the same 90-day renewal cadence used for tutors.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("application", "FK", "Tutee application being renewed"),
            ("profile", "FK", "Profile submitting the renewal"),
            ("school_id", "Image", "Re-uploaded school identification card"),
            ("enrollment_proof", "File", "Re-uploaded proof of enrollment"),
            ("reviewed_by", "FK", "Admin who reviewed the renewal"),
            ("reason_to_tutor", "Text", "Message shown to the user about the renewal"),
            ("status", "Varchar(20)", "Pending Review / Approved / Rejected"),
            ("rejection_reason", "Text", "Reason given when the renewal was rejected"),
            ("reviewed_at", "Datetime", "Time the renewal was reviewed"),
            ("submitted_at", "Datetime", "Renewal submission timestamp"),
            ("updated_at", "Datetime", "Last update timestamp"),
        ],
    ),

    # ---------------- 8. Communication ----------------
    dict(
        name="chat_room",
        pk="id",
        fks=[
            "tutee -> user_profile",
            "tutor -> user_profile",
            "booking -> booking",
        ],
        unique="(tutee, tutor) must be unique when no booking is attached, so only one "
               "pre-booking inquiry chat can exist between a given pair",
        desc="This table stores the conversation channels between users. A room attached to a "
             "booking is a session chat; a room with no booking is a pre-booking inquiry. Support "
             "rooms carry an admin conversation for a ticket.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("tutee", "FK", "Tutee participant"),
            ("tutor", "FK", "Tutor participant"),
            ("booking", "FK", "Booking the chat belongs to; empty for an inquiry"),
            ("created_at", "Datetime", "Room creation timestamp"),
            ("updated_at", "Datetime", "Time of the latest activity"),
            ("room_type", "Varchar(10)", "Regular / Support"),
        ],
    ),
    dict(
        name="message",
        pk="id",
        fks=[
            "room -> chat_room",
            "sender -> auth_users",
        ],
        unique=None,
        desc="This table stores individual chat messages. Besides text sent by users, the system "
             "writes system and booking-event messages into the same stream so that a "
             "conversation shows the full history of a session.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("room", "FK", "Chat room the message belongs to"),
            ("sender", "FK", "User who sent the message; empty for system messages"),
            ("content", "Text", "Message body"),
            ("message_type", "Varchar(20)", "Text / System / Booking event"),
            ("metadata", "JSON", "Structured payload for system and booking-event messages"),
            ("created_at", "Datetime", "Time the message was sent"),
            ("is_read", "Boolean", "Indicates if the recipient has read the message"),
            ("read_at", "Datetime", "Time the message was read"),
        ],
    ),
    dict(
        name="notification",
        pk="id",
        fks=["recipient -> user_profile"],
        unique=None,
        desc="This table stores in-app notifications raised by the system, such as a new booking "
             "request, a booking response, or a payment confirmation.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("recipient", "FK", "Profile the notification is addressed to"),
            ("message", "Varchar(255)", "Notification text"),
            ("is_read", "Boolean", "Indicates if the recipient has read it"),
            ("created_at", "Datetime", "Time the notification was raised"),
        ],
    ),
    dict(
        name="support_ticket",
        pk="id",
        fks=[
            "user -> user_profile",
            "booking -> booking",
            "transaction -> transaction",
            "penalized_user -> user_profile",
            "chatroom -> chat_room",
            "assigned_agent -> user_profile",
            "escalated_by -> user_profile",
        ],
        unique="chatroom is unique (one ticket per support chat room)",
        desc="This table stores user-reported issues and system-raised disputes. Tickets are "
             "handled by an Institution Admin and may be escalated to a Super Admin. A ticket "
             "raised for a late cancellation can also record which user was penalized and the "
             "wallet entry that applied the penalty.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("user", "FK", "User who raised the ticket"),
            ("category", "Varchar(20)", "Payment / Booking / Technical / Dispute / Other / Late Cancellation"),
            ("subject", "Varchar(150)", "Short title of the issue"),
            ("description", "Text", "Full description of the issue"),
            ("status", "Varchar(20)", "Open / In Progress / Escalated / Resolved"),
            ("reported_by_system", "Boolean", "Indicates the ticket was raised automatically"),
            ("resolution_verdict", "Varchar(10)", "Excused / Counted"),
            ("booking", "FK", "Booking the ticket concerns"),
            ("transaction", "FK", "Wallet entry applied as a penalty"),
            ("penalized_user", "FK", "User penalized by the resolution"),
            ("chatroom", "FK", "Support chat room opened for the ticket"),
            ("assigned_agent", "FK", "Admin handling the ticket"),
            ("escalation_reason", "Text", "Reason the ticket was escalated"),
            ("escalated_by", "FK", "Admin who escalated the ticket"),
            ("escalated_at", "Datetime", "Time the ticket was escalated"),
            ("created_at", "Datetime", "Ticket creation timestamp"),
            ("updated_at", "Datetime", "Last update timestamp"),
        ],
    ),

    # ---------------- 9. System records ----------------
    dict(
        name="platform_activity",
        pk="id",
        fks=["institution -> partner_institution"],
        unique=None,
        desc="This table stores the platform-wide activity feed shown on the admin dashboard, "
             "recording notable events such as registrations, completed sessions and processed "
             "withdrawals.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("activity_type", "Varchar(30)", "New User Registration / Session Completed / "
                                             "New Institution Request / Withdrawal Failure / "
                                             "Withdrawal Processed / Admin Action / "
                                             "Tutor Application / Tutee Application"),
            ("message", "Varchar(255)", "Description of the event"),
            ("institution", "FK", "Institution the event belongs to"),
            ("created_at", "Datetime", "Time the event was recorded"),
        ],
    ),
    dict(
        name="email_send_log",
        pk="id",
        fks=[],
        unique=None,
        desc="This table is an audit row written for every outbound email attempt. It backs the "
             "per-recipient send cap and gives administrators a queryable history of what was "
             "sent and what failed.",
        rows=[
            ("id", "Int (PK)", "Auto-generated primary key"),
            ("recipient", "Varchar(254)", "Address the email was sent to"),
            ("purpose", "Varchar(32)", "Login OTP / Password reset / Password changed / "
                                       "Document renewal reminder / Booking confirmed"),
            ("status", "Varchar(16)", "Sent / Failed"),
            ("error", "Text", "Error detail recorded when the send failed"),
            ("created_at", "Datetime", "Time the send was attempted"),
        ],
    ),
]

INTRO = (
    "The StudyBuddy database consists of 35 tables grouped into nine functional areas: identity "
    "and authentication, academic taxonomy, tutor profiles, scheduling, bookings and sessions, "
    "payments and wallet, verification, communication, and system records. The tables are "
    "presented below in that order. Tables marked as built in are generated by the Django "
    "framework or by the SimpleJWT authentication library rather than defined by the researchers."
)
